create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    password_hash text not null,
    full_name text,
    created_at timestamptz default now()
);

create table if not exists public.analysis_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint references public.users(id),
    filename text not null,
    resume_skills text,
    skill_cluster_distribution text,
    industries_detected text,
    created_at timestamptz default now()
);

create table if not exists public.role_results (
    id bigint generated by default as identity primary key,
    session_id bigint not null references public.analysis_sessions(id),
    job_role text not null,
    industry text,
    match_percentage double precision not null,
    ai_semantic_similarity double precision not null,
    matched_skills text,
    missing_skills text,
    recommendations text,
    transferability_data text,
    apply_at text,
    jobs_analyzed integer default 0
);

create index if not exists analysis_sessions_user_id_idx
    on public.analysis_sessions(user_id);

create index if not exists role_results_session_id_idx
    on public.role_results(session_id);

alter table public.users enable row level security;
alter table public.analysis_sessions enable row level security;
alter table public.role_results enable row level security;
